name: myworkflow

on:  
  push:
    branches:
      - main
      - feature
jobs:
   my_first_job:
            name: My first job
   my_second_job:
            name: My second jobb
       runs-on: runner-1
         
          

    
  
        

 

