name: my frist workflow

on: 
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  job:
   name: test
   runs-on: runner-1

   steps:
     - name: my frist  step
       run: Runs command-line programs that do not exceed 21,000 characters using the operating system's shell.
            If you do not provide a name, the step name will default to the text specified in the run command.
 

  
  
