name:  "my first workflow"
on:
  push:
   branches:
     - main
     - feature
jobs:
   job:
    name: display version
    runs-on: runner-1
    steps:

    - name: Checkout
      uses: actions/checkout@v5.0.0
 
 
    - name: Terraform installer
 
      uses: autero1/action-terraform@v3.0.1 

  
  
