name: my frist workflow

on: 
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  job:
   name: test
   runs-on: runner-1

   steps:
     - name: my frist  step
       run: echo i love my india
 

  
  
